// frontend/src/app/login/page.tsx
"use client";

import { User } from "@/interfaces/user";
import ServerRequestService  from "../server-request";
export default function Home(){

    async function submitForm(event : React.FormEvent<HTMLFormElement>){
        event.preventDefault();

        const formData = new FormData(event.currentTarget);

        const user: User = {
            username: formData.get("username") as string,
            mail: "",
            password: formData.get("password") as string
        }
        const response = await ServerRequestService().login(user);
        console.log(response);
    };

    return <form onSubmit={submitForm}>
        <a href="/">HOME PAGE</a> <br/>
        <div>
            <label>Username</label>
            <input type="text" name="username"/>
        </div>
        <div>
            <label>password</label>
            <input type="password" name="password"/>
        </div>
        <button type="submit">SUBMIT</button>
    </form>
}

// frontend/src/app/login/login.component.ts
import { Component, inject } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';

import { User } from '../interfaces/user';

import { ServerRequestService } from '../services/server-request.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent 
{
  http = inject(ServerRequestService)

  applyForm = new FormGroup({
    name: new FormControl('', [Validators.required, Validators.minLength(4), Validators.maxLength(10)]),
    password: new FormControl('', [Validators.required, Validators.minLength(3), Validators.maxLength(10)])
  });

  async submitForm() {
    // if(!this.applyForm.valid)
    //   return;

    const user: User = {
      username: this.applyForm.value.name as string,
      mail: "",
      password: this.applyForm.value.password as string
    }
    
    console.log(await this.http.login(user));
  }
}

<form [formGroup]="applyForm" (ngSubmit)="submitForm()">
    <div class="form-group">
        <label for="">Username</label>
        <input type="text" formControlName="name">
    </div>
    <div class="form-group">
        <label for="">password</label>
        <input type="password" formControlName="password">
    </div>
    <button type="submit">SUBMIT</button>
</form>
