// frontend/src/app/register/page.tsx
"use client";

import ServerRequestService  from "../server-request";
import { User } from "@/interfaces/user";

export default function Home() {
    async function submitForm(event : React.FormEvent<HTMLFormElement>): Promise<void> {
        event.preventDefault();
    
        const formData = new FormData(event.currentTarget);

        const user: User = {
            username: formData.get("username") as string,
            mail: formData.get("mail") as string,
            password: formData.get("password") as string
        }
        
        const response = await ServerRequestService().register(user);
        console.log(response);
      }
    return (
        <form onSubmit={submitForm}>
            <div>
                <label>Username</label>
                <input type="text" name="username"/>
            </div>
            <div>
                <label>E-mail</label>
                <input type="mail" name="mail"/>
            </div>
            <div>
                <label>password</label>
                <input type="password" name="password"/>
            </div>
            <button type="submit">SUBMIT</button>
        </form>
    );
};

// frontend/src/app/register/register.component.ts
import { Component, inject } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';

import { User } from '../interfaces/user';

import { ServerRequestService } from '../services/server-request.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './register.component.html',
  styleUrl: './register.component.css'
})

export class RegisterComponent
{
  http = inject(ServerRequestService)

  applyForm = new FormGroup({
    name: new FormControl('', [Validators.required, Validators.minLength(4), Validators.maxLength(10)]),
    mail: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required, Validators.minLength(3), Validators.maxLength(10)])
  });

  async submitForm() {
    // if(!this.applyForm.valid)
    //   return;

    const user: User = {
      username: this.applyForm.value.name as string,
      mail: this.applyForm.value.mail as string,
      password: this.applyForm.value.password as string
    }
    
    console.log(await this.http.register(user));
  }
}

<form [formGroup]="applyForm" (ngSubmit)="submitForm()">
    <div class="form-group">
        <label for="">Username</label>
        <input type="text" formControlName="name">
    </div>
    <div class="form-group">
        <label for="">E-mail</label>
        <input type="mail" formControlName="mail">
    </div>
    <div class="form-group">
        <label for="">password</label>
        <input type="password" formControlName="password">
    </div>
    <button type="submit">SUBMIT</button>
</form>
